### ISSUE TITLE
get the play idempotent: 2 propositions

### ISSUE THREAD

**Issue by fdutheil** [William-Yeh/ansible-oracle-java#1]
Hi,
I'm getting this play on Debian Wheezy working, with 2 changes to get it almost perfect. 
In use-apt.yml:

```
- name: Import WebUpd8 PGP key
  sudo: True
  # command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
  apt_key: keyserver=keyserver.ubuntu.com id=0xEEA14886 state=present

- name: automatically accept the Oracle license
  sudo: True
  # shell: echo "oracle-java{{ java_version }}-installer" shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  debconf: name="oracle-java{{ java_version }}-installer" question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
```

Like this, running the play again won't report 2 "changed" states when it shouldn't.

Another suggestion: why forcing sudo on tasks level? Wouldn't it be better to let people set sudo on/off in their inventory?

Regards,
Florent

**Comment by William-Yeh** [comment]
Hi Florent,

Thanks for these suggestions. I'll try them several days later.

**Comment by William-Yeh** [comment]
Hi Florent,

About your second question:

> why forcing sudo on tasks level? Wouldn't it be better to let people set sudo on/off in their inventory?

I want my reusable roles to be used in either ways:
1. Client playbook without `sudo`:

``` yaml
---
# file: playbook-without-sudo.yml

- hosts: all
  roles:
    - williamyeh.oracle-java
    - ...
  tasks:
    ...
```
1. Client playbook with `sudo`:

``` yaml
---
# file: playbook-with-sudo.yml

- hosts: all
  sudo: True
  roles:
    - williamyeh.oracle-java
    - ...
  tasks:
    ...
```

I don't know if there's any official or de facto best practice regarding this. Any comment?
