### ISSUE TITLE
Update to support jdk 8u121

### ISSUE THREAD

**Issue by hansdg1** [William-Yeh/ansible-oracle-java#58]
Please add support for Oracle jdk 8u121. I tried specifying it manually using this, but it won't download.
```
  vars:
    java_version: 8
    java_subversion: 121
    java_build: 13
```

`fatal: [XXX]: FAILED! => {"changed": false, "dest": "/tmp/jdk-8u121-linux-x64.rpm", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.oracle.com/otn-pub/java/jdk/8u121-b13/jdk-8u121-linux-x64.rpm"}`
